In [60]:
import pandas as pd
import numpy as np

In [61]:
df = pd.read_csv('/content/play_tennis.csv')

In [62]:
df = df.drop(columns=['day'])
df

     outlook  temp humidity    wind play
0      Sunny   Hot     High    Weak   No
1      Sunny   Hot     High  Strong   No
2   Overcast   Hot     High    Weak  Yes
3       Rain  Mild     High    Weak  Yes
4       Rain  Cool   Normal    Weak  Yes
5       Rain  Cool   Normal  Strong   No
6   Overcast  Cool   Normal  Strong  Yes
7      Sunny  Mild     High    Weak   No
8      Sunny  Cool   Normal    Weak  Yes
9       Rain  Mild   Normal    Weak  Yes
10     Sunny  Mild   Normal  Strong  Yes
11  Overcast  Mild     High  Strong  Yes
12  Overcast   Hot   Normal    Weak  Yes
13      Rain  Mild     High  Strong   No

In [63]:
# Problem 1

# Outlook = Sunny
# Temp = Hot
# Humidity = High
# Wind = Weak

# Play or No Play?

In [64]:
# Solution

# P(Yes | Sunny, Hot, High, Weak)
# = P(Sunny | Yes) * P(Hot | Yes) * P(High | Yes) * P(Weak | Yes) * P(Yes)

# P(No | Sunny, Hot, High, Weak)
# = P(Sunny | No) * P(Hot | No) * P(High | No) * P(Weak | No) * P(No)

# Compare both probabilities and choose the class
# using the Maximum A Posteriori (MAP) rule.

In [65]:
# Problem 2

# Outlook = Overcast
# Temp = Cold
# Humidity = Low
# Wind = Weak

# Play or No Play?

In [66]:
df['play'].value_counts()

play
Yes    9
No     5
Name: count, dtype: int64

In [91]:
py=9/14
pn=5/14

In [68]:
print(py)
print(pn)

0.6428571428571429
0.35714285714285715

In [69]:
#Outlook

pd.crosstab(df['outlook'],df['play'])

play      No  Yes
outlook
Overcast   0    4
Rain       2    3
Sunny      3    2

In [88]:
povern=0
prainn=2/5
psunnyn=3/5
povery=4/9
prainy=3/9
psunnyy=2/9

In [71]:
pd.crosstab(df['humidity'],df['play'])

play      No  Yes
humidity
High       4    3
Normal     1    6

In [87]:
phighn=4/5
phighy=3/9
pnormn=1/5
pnormy=6/9

In [73]:
pd.crosstab(df['temp'],df['play'])

play  No  Yes
temp
Cool   1    3
Hot    2    2
Mild   2    4

In [86]:
pcoldn=1/5
photn=2/5
pmildn=2/5

pcoldy=3/9
photy=2/9
pmildy=4/9

In [75]:
pd.crosstab(df['wind'],df['play'])

play    No  Yes
wind
Strong   3    3
Weak     2    6

In [85]:
pstn=3/5
pweakn=2/5

psty=3/9
pweaky=6/9

In [92]:
#Problem1
pn=psunnyn * photn * phighn * pweakn * pn
py=psunnyy * photy * phighy * pweaky * py

In [93]:
if pn>py :
  print('No','pn=',pn,'py=',py)
else:
  print('Yes',pn,py)

No pn= 0.02742857142857143 py= 0.007054673721340387

In [94]:
#Problem2
pn=povern * pcoldn * phighn * pweakn * pn
py=povery * pcoldy * phighy * pweaky * py

In [95]:
if pn>py :
  print('No','pn=',pn,'py=',py)
else:
  print('Yes',pn,py)

Yes 0.0 0.00023225263280132958