In [ ]:
import pandas as pd
import requests

In [ ]:
res=requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page=1')

In [ ]:
df=pd.DataFrame(res.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]

,id,title,overview,release_date,popularity,vote_average,vote_count
0,1007757,Swapped,"A small woodland creature and a majestic bird,...",2026-05-01,141.9467,8.960,1798
1,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,94.2467,8.700,30627
2,936075,Michael,"The story of Michael Jackson, one of the most ...",2026-04-22,372.0563,8.694,3019
3,687163,Project Hail Mary,Science teacher Ryland Grace wakes up on a spa...,2026-03-15,132.5652,8.688,5395
4,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,42.7720,8.687,23077
5,1330021,Remarkably Bright Creatures,Through unlikely bonds formed during night shi...,2026-05-07,29.4338,8.573,668
6,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,1974-12-20,29.1707,8.571,13994
7,424,Schindler's List,The true story of how businessman Oskar Schind...,1993-12-15,25.2603,8.570,17542
8,389,12 Angry Men,The defense and the prosecution have rested an...,1957-04-10,22.0325,8.563,10065
9,1383731,Instinto protector,Nikki's life is shattered when her daughter is...,2026-02-20,25.5743,8.548,356
10,129,Spirited Away,"A young girl, Chihiro, becomes trapped in a st...",2001-07-20,37.4771,8.500,18452
11,155,The Dark Knight,Batman raises the stakes in his war on crime. ...,2008-07-16,52.7406,8.531,35961
12,19404,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second...",1995-10-20,16.2176,8.510,4598
13,497,The Green Mile,A supernatural tale set on death row in a Sout...,1999-12-10,29.8572,8.500,19360
14,122,The Lord of the Rings: The Return of the King,As armies mass for a final battle that will de...,2003-12-17,39.6021,8.500,26700
15,1181678,¿Quieres ser mi hijo?,"Lu, a conformist woman in her forties, learns ...",2023-09-21,10.4550,8.500,355
16,496243,Parasite,"All unemployed, Ki-taek's family takes peculia...",2019-05-30,35.5239,8.500,20779
17,680,Pulp Fiction,"A burger-loving hit man, his philosophical par...",1994-09-10,42.9266,8.482,30331
18,372058,Your Name.,High schoolers Mitsuha and Taki are complete s...,2016-07-01,29.2805,8.482,12646
19,157336,Interstellar,The adventures of a group of explorers who mak...,2014-11-05,69.0112,8.479,40109

In [ ]:
df= pd.DataFrame()

In [ ]:
df

Empty DataFrame
Columns: []
Index: []

In [ ]:
for i in range(1,429):
  res=requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page={}'.format(i))
  temp_df=pd.DataFrame(res.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]
  df = pd.concat([df, temp_df], ignore_index=True)

In [ ]:
df

,id,title,overview,release_date,popularity,vote_average,vote_count
0,1007757,Swapped,"A small woodland creature and a majestic bird,...",2026-05-01,141.9467,8.960,1798
1,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,94.2467,8.700,30627
2,936075,Michael,"The story of Michael Jackson, one of the most ...",2026-04-22,372.0563,8.694,3019
3,687163,Project Hail Mary,Science teacher Ryland Grace wakes up on a spa...,2026-03-15,132.5652,8.688,5395
4,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,42.7720,8.687,23077
...,...,...,...,...,...,...,...
8555,14400,The Heir Apparent: Largo Winch,"After a powerful billionaire is murdered, his ...",2008-12-17,2.2615,6.040,591
8556,12590,Below,In the dark silence of the sea during World Wa...,2002-08-11,1.7572,6.040,518
8557,10433,Mad Dog and Glory,Wayne Dobie is a shy cop whose low-key demeano...,1993-03-05,1.8547,6.000,403
8558,9948,The Fox and the Hound 2,"Best friends Tod, a fox kit, and Copper, a hou...",2006-11-09,2.9986,6.040,712
8559,675531,Dark Harvest,"In a small Midwestern town, a deadly annual ri...",2023-10-11,2.0409,6.000,309

In [ ]:
df.to_csv('movies.csv')

In [ ]:
import requests
import pandas as pd

all_data = []

url = "https://weatherbit-v1-mashape.p.rapidapi.com/forecast/3hourly"

headers = {
    "x-rapidapi-host": "weatherbit-v1-mashape.p.rapidapi.com",
    "x-rapidapi-key": "2911aab065msh1001b0054442f7ap1e0740jsnaec496ef19f4"
}

# loop through pages
for page in range(1, 500):   # page 1 to 3
    querystring = {
        "lat": "35.5",
        "lon": "-78.5",
        "units": "imperial",
        "lang": "en",
        "page": page
    }

    response = requests.get(url, headers=headers, params=querystring)

    data = response.json()

    # some APIs may not have 'data', so we check
    if "data" in data:
        all_data.extend(data["data"])

# convert to dataframe
df = pd.DataFrame(all_data)

print(df.head())

   app_temp  clouds  clouds_hi  clouds_low  clouds_mid       datetime  dewpt  \
0      72.1      60          0          12           2  2026-06-27:11   70.7
1      76.5      59          0          14           2  2026-06-27:12   73.8
2      79.3      55          0          12          12  2026-06-27:13   74.1
3      86.0      51          0           6           4  2026-06-27:14   74.7
4      91.8      43          0           7           0  2026-06-27:15   75.4

   dhi  dni  ghi  ...        timestamp_utc          ts  uv   vis  \
0   51  463  124  ...  2026-06-27T11:00:00  1782558000   1   7.6
1   78  673  320  ...  2026-06-27T12:00:00  1782561600   1   7.8
2   96  784  525  ...  2026-06-27T13:00:00  1782565200   2   8.8
3  108  851  713  ...  2026-06-27T14:00:00  1782568800   4  10.9
4  117  893  866  ...  2026-06-27T15:00:00  1782572400   6  13.6

                                             weather  wind_cdir  \
0  {'description': 'Broken clouds', 'icon': 'c03d...         SW
1  {'description': 'Broken clouds', 'icon': 'c03d...         SW
2  {'description': 'Broken clouds', 'icon': 'c03d...         SW
3  {'description': 'Broken clouds', 'icon': 'c03d...         SW
4  {'description': 'Broken clouds', 'icon': 'c03d...        WSW

   wind_cdir_full  wind_dir  wind_gust_spd  wind_spd
0       southwest       220            8.1       4.0
1       southwest       230            8.9       4.9
2       southwest       230            9.2       5.1
3       southwest       230            9.6       5.6
4  west-southwest       240           11.0       6.3

[5 rows x 32 columns]

In [ ]:
df.to_csv('weather1.csv')