In [17]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split, GridSearchCV

from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer,KNNImputer
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression

In [8]:
df = pd.read_csv('train (1).csv',usecols=['Age','Pclass','Fare','Survived'])

In [9]:
df.head()

   Survived  Pclass   Age     Fare
0         0       3  22.0   7.2500
1         1       1  38.0  71.2833
2         1       3  26.0   7.9250
3         1       1  35.0  53.1000
4         0       3  35.0   8.0500

In [11]:
df.isnull().mean()*100

Survived     0.00000
Pclass       0.00000
Age         19.86532
Fare         0.00000
dtype: float64

In [12]:
X = df.drop(columns=['Survived'])
y = df['Survived']

In [13]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)

In [14]:
X_train.head()

     Pclass   Age     Fare
30        1  40.0  27.7208
10        3   4.0  16.7000
873       3  47.0   9.0000
182       3   9.0  31.3875
876       3  20.0   9.8458

In [53]:
knn=KNNImputer(n_neighbors=1,weights='distance')

X_train_trf=knn.fit_transform(X_train)
X_test_trf=knn.transform(X_test)

In [54]:
pd.DataFrame(X_train_trf,columns=X_train.columns)

     Pclass   Age      Fare
0       1.0  40.0   27.7208
1       3.0   4.0   16.7000
2       3.0  47.0    9.0000
3       3.0   9.0   31.3875
4       3.0  20.0    9.8458
..      ...   ...       ...
707     3.0  30.0    8.6625
708     3.0  31.0    8.7125
709     1.0  71.0   49.5042
710     1.0  18.0  221.7792
711     1.0  49.0   25.9250

[712 rows x 3 columns]

In [55]:
lr=LogisticRegression()

lr.fit(X_train_trf,y_train)

y_pred=lr.predict(X_test_trf)

In [56]:
accuracy_score(y_test,y_pred)

0.7206703910614525