In [10]:
import pandas as pd

In [11]:
df = pd.read_csv("/content/heart.csv")

In [12]:
df.head()

   age  sex  cp  trestbps  chol  fbs  ...  exang  oldpeak  slope  ca  thal  target
0   63    1   3       145   233    1  ...      0      2.3      0   0     1       1
1   37    1   2       130   250    0  ...      0      3.5      0   0     2       1
2   41    0   1       130   204    0  ...      0      1.4      2   0     2       1
3   56    1   1       120   236    0  ...      0      0.8      2   0     2       1
4   57    0   0       120   354    0  ...      1      0.6      2   0     2       1

[5 rows x 14 columns]

In [13]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

In [14]:
X_train,X_test,y_train,y_test=train_test_split(df.iloc[:,0:-1],df.iloc[:,-1],test_size=0.2,random_state=2)

In [15]:
clf1=LogisticRegression()
clf2=DecisionTreeClassifier()

In [16]:
clf1.fit(X_train,y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [17]:
clf2.fit(X_train,y_train)

DecisionTreeClassifier()

In [18]:
y_pred1=clf1.predict(X_test)
y_pred2=clf2.predict(X_test)

In [19]:
from sklearn.metrics import accuracy_score,confusion_matrix,f1_score,precision_score,recall_score
print("Accuracy of Logistic Regression",accuracy_score(y_test,y_pred1))
print("Accuracy of Decision Trees",accuracy_score(y_test,y_pred2))

Accuracy of Logistic Regression 0.9016393442622951
Accuracy of Decision Trees 0.8360655737704918

In [20]:
confusion_matrix(y_test,y_pred1)

array([[26,  6],
       [ 0, 29]])

In [21]:
print("Logistic Regression Confusion Matrix\n")
pd.DataFrame(confusion_matrix(y_test,y_pred1),columns=list(range(0,2)))

Logistic Regression Confusion Matrix

    0   1
0  26   6
1   0  29

In [22]:
print("Decision Tree Confusion Matrix\n")
pd.DataFrame(confusion_matrix(y_test,y_pred2),columns=list(range(0,2)))

Decision Tree Confusion Matrix

    0   1
0  25   7
1   3  26

In [23]:
result = pd.DataFrame()
result['Actual Label'] = y_test
result['Logistic Regression Prediction'] = y_pred1
result['Decision Tree Prediction'] = y_pred2

In [24]:
result

     Actual Label  Logistic Regression Prediction  Decision Tree Prediction
99              1                               1                         1
296             0                               1                         0
89              1                               1                         1
30              1                               1                         1
234             0                               0                         1
..            ...                             ...                       ...
173             0                               0                         1
94              1                               1                         1
161             1                               1                         1
216             0                               1                         1
91              1                               1                         1

[61 rows x 3 columns]

In [25]:
print("For Logistic regression Model")
print("-"*50)
cdf = pd.DataFrame(confusion_matrix(y_test,y_pred1),columns=list(range(0,2)))
print(cdf)
print("-"*50)
print("Precision - ",precision_score(y_test,y_pred1))
print("Recall - ",recall_score(y_test,y_pred1))
print("F1 score - ",f1_score(y_test,y_pred1))

For Logistic regression Model
--------------------------------------------------
    0   1
0  26   6
1   0  29
--------------------------------------------------
Precision -  0.8285714285714286
Recall -  1.0
F1 score -  0.90625

In [26]:
print("For DT Model")
print("-"*50)
cdf = pd.DataFrame(confusion_matrix(y_test,y_pred2),columns=list(range(0,2)))
print(cdf)
print("-"*50)
print("Precision - ",precision_score(y_test,y_pred2))
print("Recall - ",recall_score(y_test,y_pred2))
print("F1 score - ",f1_score(y_test,y_pred2))

For DT Model
--------------------------------------------------
    0   1
0  25   7
1   3  26
--------------------------------------------------
Precision -  0.7878787878787878
Recall -  0.896551724137931
F1 score -  0.8387096774193549

In [27]:
precision_score(y_test,y_pred1,average=None)

array([1.        , 0.82857143])

In [29]:
recall_score(y_test,y_pred2,average=None)

array([0.78125   , 0.89655172])