In [94]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split,cross_val_score
from sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.compose import ColumnTransformer

In [95]:
df = pd.read_csv('train.csv')[['Age','Fare','SibSp','Parch','Survived']]

In [96]:
df.head()

    Age     Fare  SibSp  Parch  Survived
0  22.0   7.2500      1      0         0
1  38.0  71.2833      1      0         1
2  26.0   7.9250      0      0         1
3  35.0  53.1000      1      0         1
4  35.0   8.0500      0      0         0

In [97]:
df.dropna(inplace=True)

In [98]:
df['Family']=df['Parch']+df['SibSp']

In [99]:
df.head()

    Age     Fare  SibSp  Parch  Survived  Family
0  22.0   7.2500      1      0         0       1
1  38.0  71.2833      1      0         1       1
2  26.0   7.9250      0      0         1       0
3  35.0  53.1000      1      0         1       1
4  35.0   8.0500      0      0         0       0

In [100]:
df.drop(columns=['SibSp','Parch'],inplace=True)

In [104]:
X=df.drop(columns=['Survived'])
y=df.iloc[:,-2]

In [105]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [106]:
clf=DecisionTreeClassifier(random_state=42)

clf.fit(X_train,y_train)

y_pred=clf.predict(X_test)

accuracy_score(y_test,y_pred)

0.6223776223776224

In [107]:
np.mean(cross_val_score(DecisionTreeClassifier(),X,y,cv=10,scoring='accuracy'))

np.float64(0.6499217527386542)

In [109]:
from sklearn.preprocessing import Binarizer

trf=ColumnTransformer([
    ('bin',Binarizer(copy=False),['Family'])
],remainder='passthrough')

X_train_trf=trf.fit_transform(X_train)
X_test_trf=trf.fit_transform(X_test)

In [112]:
pd.DataFrame(X_train_trf,columns=['Family','Age','Fare'])

     Family   Age      Fare
0       1.0  31.0   20.5250
1       1.0  26.0   14.4542
2       1.0  30.0   16.1000
3       0.0  33.0    7.7750
4       0.0  25.0   13.0000
..      ...   ...       ...
566     1.0  46.0   61.1750
567     0.0  25.0   13.0000
568     0.0  41.0  134.5000
569     1.0  33.0   20.5250
570     0.0  33.0    7.8958

[571 rows x 3 columns]

In [113]:
clf=DecisionTreeClassifier(random_state=42)

clf.fit(X_train_trf,y_train)

y_pred=clf.predict(X_test_trf)

accuracy_score(y_test,y_pred)

0.6433566433566433

In [118]:
X_trf = trf.fit_transform(X)
np.mean(cross_val_score(DecisionTreeClassifier(),X_trf,y,cv=10,scoring='accuracy'))

np.float64(0.629049295774648)